In [12]:
import pandas as pd

In [15]:
df = pd.read_csv("crime_and_incarceration_by_state.csv")
df.head(5)

,jurisdiction,includes_jails,year,prisoner_count,crime_reporting_change,crimes_estimated,state_population,violent_crime_total,murder_manslaughter,rape_legacy,rape_revised,robbery,agg_assault,property_crime_total,burglary,larceny,vehicle_theft
0,FEDERAL,False,2001,149852,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ALABAMA,False,2001,24741,False,False,4468912.0,19582.0,379.0,1369.0,NaN,5584.0,12250.0,173253.0,40642.0,119992.0,12619.0
2,ALASKA,True,2001,4570,False,False,633630.0,3735.0,39.0,501.0,NaN,514.0,2681.0,23160.0,3847.0,16695.0,2618.0
3,ARIZONA,False,2001,27710,False,False,5306966.0,28675.0,400.0,1518.0,NaN,8868.0,17889.0,293874.0,54821.0,186850.0,52203.0
4,ARKANSAS,False,2001,11489,False,False,2694698.0,12190.0,148.0,892.0,NaN,2181.0,8969.0,99106.0,22196.0,69590.0,7320.0

In [7]:
df.columns

Index(['jurisdiction', 'includes_jails', 'year', 'prisoner_count',
       'crime_reporting_change', 'crimes_estimated', 'state_population',
       'violent_crime_total', 'murder_manslaughter', 'rape_legacy',
       'rape_revised', 'robbery', 'agg_assault', 'property_crime_total',
       'burglary', 'larceny', 'vehicle_theft'],
      dtype='object')

In [8]:
df.describe()

,year,prisoner_count,state_population,violent_crime_total,murder_manslaughter,rape_legacy,rape_revised,robbery,agg_assault,property_crime_total,burglary,larceny,vehicle_theft
count,816.000000,816.000000,7.990000e+02,799.000000,799.000000,749.000000,199.000000,799.000000,799.000000,7.990000e+02,799.000000,799.000000,799.000000
mean,2008.500000,28606.033088,6.072322e+06,26228.459324,313.702128,1788.339119,2406.195980,7696.824781,16256.270338,1.878006e+05,40870.408010,127912.287860,19017.904881
std,4.612599,39556.940699,6.725500e+06,33866.838388,386.019821,1865.443299,2550.486639,11107.478615,20849.515589,2.138503e+05,47829.948836,139434.591858,30780.350362
min,2001.000000,1088.000000,4.937540e+05,496.000000,5.000000,99.000000,110.000000,43.000000,270.000000,8.806000e+03,1689.000000,6660.000000,178.000000
25%,2004.750000,5698.000000,1.790026e+06,5213.000000,48.500000,571.000000,780.000000,1106.000000,3529.000000,4.749750e+04,9406.000000,32765.500000,4191.000000
50%,2008.500000,16915.000000,4.314113e+06,15744.000000,179.000000,1238.000000,1723.000000,3933.000000,10083.000000,1.327730e+05,27698.000000,95079.000000,10583.000000
75%,2012.250000,30920.500000,6.808844e+06,31843.000000,429.000000,2092.000000,2680.000000,8702.000000,20308.000000,2.259575e+05,47941.000000,155688.000000,20872.500000
max,2016.000000,216915.000000,3.929648e+07,212867.000000,2503.000000,10198.000000,13702.000000,71142.000000,136087.000000,1.227194e+06,250521.000000,731486.000000,257543.000000

In [9]:
df.isnull().sum()

jurisdiction                0
includes_jails              0
year                        0
prisoner_count              0
crime_reporting_change     17
crimes_estimated           17
state_population           17
violent_crime_total        17
murder_manslaughter        17
rape_legacy                67
rape_revised              617
robbery                    17
agg_assault                17
property_crime_total       17
burglary                   17
larceny                    17
vehicle_theft              17
dtype: int64

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 816 entries, 0 to 815
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   jurisdiction            816 non-null    object
 1   includes_jails          816 non-null    bool
 2   year                    816 non-null    int64
 3   prisoner_count          816 non-null    int64
 4   crime_reporting_change  799 non-null    object
 5   crimes_estimated        799 non-null    object
 6   state_population        799 non-null    float64
 7   violent_crime_total     799 non-null    float64
 8   murder_manslaughter     799 non-null    float64
 9   rape_legacy             749 non-null    float64
 10  rape_revised            199 non-null    float64
 11  robbery                 799 non-null    float64
 12  agg_assault             799 non-null    float64
 13  property_crime_total    799 non-null    float64
 14  burglary                799 non-null    float64
 15  larceny                 799 non-null    float64
 16  vehicle_theft           799 non-null    float64
dtypes: bool(1), float64(11), int64(2), object(3)
memory usage: 102.9+ KB